listening-port=3478
fingerprint
lt-cred-mech
realm=__PUBLIC_HOST__
user=__TURN_USER__:__TURN_PASSWORD__
external-ip=__PUBLIC_IP__/__PRIVATE_IP__
min-port=49160
max-port=49200
no-cli
no-multicast-peers
