#!/usr/bin/env python3
"""Build the pinned upstream engine with explicit, reviewable integration edits."""
from pathlib import Path
import json
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'third-party/pvz'
STATIC = ROOT / 'game-service/src/main/resources/static'

def build():
    parts = ['/* Generated by scripts/build-pvz-vendor.py. MIT (c) 2018 Yang Yunhe.\n'
             ' * Original sources and license: third-party/pvz. Do not hand-edit. */\n'
             'window.PvZUpstream = (function () {\n'
             'const setTimeout = (...args) => window.PvZLifetime.clock.timeout(...args);\n'
             'const setInterval = (...args) => window.PvZLifetime.clock.interval(...args);\n'
             'const clearTimeout = id => window.PvZLifetime.clock.cancel(id);\n'
             'const clearInterval = clearTimeout;\nconst imageCache = new Map();\n']
    for name in ['common.js','scene.js','game.js','main.js']:
        code = (SOURCE/'js'/name).read_text()
        if name == 'common.js':
            code = code.replace("  let img = new Image()\n  img.src = './images/' + src\n  return img", "  if (imageCache.has(src)) return imageCache.get(src)\n  let img = new Image()\n  img.src = 'assets/pvz/images/' + src\n  imageCache.set(src, img)\n  return img")
        if name == 'scene.js':
            code = code.replace("document.getElementsByTagName('body')[0]", "document.getElementById('pvzWorld')")
            code = code.replace("img.src = 'images/sun.gif'", "img.src = 'assets/pvz/images/sun.gif'")
            code = code.replace('self.timer = setTimeout', 'self.cooldownTimer = setTimeout')
        if name == 'game.js':
            code = code.replace('window.addEventListener(', 'window.PvZLifetime.listen(')
        if name == 'main.js':
            code = code.replace('Math.ceil(Math.random() * 4 + 1)', 'Math.floor(Math.random() * 5) + 1')
            code = code.replace('window._main = new Main()\nwindow._main.start()', '')
        parts.append('\n// ---- Upstream: '+name+' ----\n'+code+'\n')
    parts.append('return {Main, Game, Plant, Zombie, Card, SunNum, Car, Animation, imageFromPath, allImg};\n})();\n')
    output = ''.join(parts)
    (STATIC/'assets/plants-engine.js').write_text(output)
    # Original CSS references remain relative to assets/pvz/pvz.css.
    css = (SOURCE/'css/style.css').read_text().replace('../images/', 'images/')
    (STATIC/'assets/pvz/pvz.css').write_text(css)
    assets=json.loads((SOURCE/'provenance.json').read_text())['assets']
    urls=['/assets/pvz/images/'+item['path'] for item in assets]+['/assets/pvz/pvz.css','/assets/pvz-clock.js']
    (ROOT/'gateway-service/src/main/resources/pvz-public-assets.txt').write_text('\n'.join(sorted(urls))+'\n')
    (STATIC/'assets/pvz/asset-list.json').write_text(json.dumps([item['path'] for item in assets]))
    manifest=ROOT/'gateway-service/src/main/resources/pvz-public-assets.txt'
    manifest.write_text(manifest.read_text()+'/assets/pvz/asset-list.json\n')
    return output

if __name__ == '__main__':
    build()
